function images = getImageFromDatasetByName(datasetIDstr, name)
    global session
        query = ['select i from Image i ' ...
            'left outer join fetch i.datasetLinks dl ' ...
            'left outer join fetch dl.parent as p ' ...
            'where p.id=' datasetIDstr ' ' ...
            ];
%             'and i.name=''' name ''' ' ...
%             ];
        images = session.getQueryService().findAllByQuery(query,[]);
        for idx=(images.size()-1):-1:0
            if ~strcmp(images.get(idx).getName().getValue(),name)
                images.remove(idx);
            end
        end
end
%             'and i.name="' name '" ' ...
