function [result]=mathematica_generated_LS_Band(Der,LevelSetFct,lambda,kappa,sigma,extensionmax,lambdaInside,lambdaOutside,lambdaContour,c1,c2,c3,Imagee,ImageeDer,epsilon,BandWidth,dl0m)
if kappa==0 || lambda==0
result1=zeros(size(LevelSetFct));
else
result1 = 2.*kappa.*lambda.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-5).*(Der(:,:,2).^6.*(( ...
  -3).*Der(:,:,3).^3+18.*Der(:,:,3).*Der(:,:,4).^2+(-6).*Der(:,:,3).* ...
  Der(:,:,7).*Der(:,:,2)+(-6).*Der(:,:,6).*Der(:,:,4).*Der(:,:,2)+ ...
  Der(:,:,10).*Der(:,:,2).^2+3.*Der(:,:,3).^2.*Der(:,:,5))+2.*Der(:,:,1).* ...
  Der(:,:,2).^5.*(30.*Der(:,:,3).^2.*Der(:,:,4)+(-18).*Der(:,:,4).^3+15.* ...
  Der(:,:,7).*Der(:,:,4).*Der(:,:,2)+Der(:,:,2).*((-2).*Der(:,:,11).*Der(:,:,2)+ ...
  3.*Der(:,:,6).*Der(:,:,5))+(-6).*Der(:,:,3).*(Der(:,:,6).*Der(:,:,2)+(-1).* ...
  Der(:,:,8).*Der(:,:,2)+4.*Der(:,:,4).*Der(:,:,5)))+(-2).*Der(:,:,1).^7.*(2.* ...
  Der(:,:,13).*Der(:,:,2)+3.*Der(:,:,8).*Der(:,:,5)+3.*Der(:,:,4).* ...
  Der(:,:,9))+(-2).*Der(:,:,1).^3.*Der(:,:,2).^3.*(42.*Der(:,:,3).^2.* ...
  Der(:,:,4)+(-60).*Der(:,:,4).^3+6.*Der(:,:,3).*(Der(:,:,6).*Der(:,:,2)+ ...
  Der(:,:,8).*Der(:,:,2)+(-16).*Der(:,:,4).*Der(:,:,5))+Der(:,:,2).*(4.* ...
  Der(:,:,11).*Der(:,:,2)+2.*Der(:,:,13).*Der(:,:,2)+(-15).*Der(:,:,8).* ...
  Der(:,:,5))+Der(:,:,4).*(6.*Der(:,:,7).*Der(:,:,2)+42.*Der(:,:,5).^2+(-9).* ...
  Der(:,:,2).*Der(:,:,9)))+(-2).*Der(:,:,1).^5.*Der(:,:,2).*(18.*Der(:,:,4).^3+ ...
  Der(:,:,2).*(12.*Der(:,:,3).*Der(:,:,8)+2.*Der(:,:,11).*Der(:,:,2)+4.* ...
  Der(:,:,13).*Der(:,:,2)+3.*Der(:,:,6).*Der(:,:,5)+(-12).*Der(:,:,8).* ...
  Der(:,:,5))+3.*Der(:,:,4).*(7.*Der(:,:,7).*Der(:,:,2)+8.*Der(:,:,3).* ...
  Der(:,:,5)+(-10).*Der(:,:,5).^2+(-2).*Der(:,:,2).*Der(:,:,9)))+ ...
  Der(:,:,1).^2.*Der(:,:,2).^4.*(21.*Der(:,:,3).^3+(-45).*Der(:,:,3).^2.* ...
  Der(:,:,5)+2.*(6.*Der(:,:,6).*Der(:,:,4).*Der(:,:,2)+(-21).*Der(:,:,4).* ...
  Der(:,:,8).*Der(:,:,2)+51.*Der(:,:,4).^2.*Der(:,:,5)+Der(:,:,2).*( ...
  Der(:,:,10).*Der(:,:,2)+3.*Der(:,:,12).*Der(:,:,2)+(-12).*Der(:,:,7).* ...
  Der(:,:,5)))+(-6).*Der(:,:,3).*(28.*Der(:,:,4).^2+(-4).*Der(:,:,7).* ...
  Der(:,:,2)+(-4).*Der(:,:,5).^2+Der(:,:,2).*Der(:,:,9)))+Der(:,:,1).^8.* ...
  Der(:,:,14)+Der(:,:,1).^4.*Der(:,:,2).^2.*(18.*Der(:,:,6).*Der(:,:,4).* ...
  Der(:,:,2)+(-12).*Der(:,:,4).*Der(:,:,8).*Der(:,:,2)+Der(:,:,10).* ...
  Der(:,:,2).^2+12.*Der(:,:,12).*Der(:,:,2).^2+24.*Der(:,:,3).^2.*Der(:,:,5)+( ...
  -168).*Der(:,:,4).^2.*Der(:,:,5)+(-12).*Der(:,:,7).*Der(:,:,2).*Der(:,:,5)+ ...
  21.*Der(:,:,5).^3+3.*Der(:,:,3).*(34.*Der(:,:,4).^2+10.*Der(:,:,7).* ...
  Der(:,:,2)+(-15).*Der(:,:,5).^2)+(-12).*Der(:,:,2).*Der(:,:,5).*Der(:,:,9)+ ...
  Der(:,:,2).^2.*Der(:,:,14))+Der(:,:,1).^6.*(30.*Der(:,:,4).*Der(:,:,8).* ...
  Der(:,:,2)+6.*Der(:,:,12).*Der(:,:,2).^2+18.*Der(:,:,4).^2.*Der(:,:,5)+12.* ...
  Der(:,:,7).*Der(:,:,2).*Der(:,:,5)+3.*Der(:,:,3).*Der(:,:,5).^2+(-3).* ...
  Der(:,:,5).^3+6.*Der(:,:,3).*Der(:,:,2).*Der(:,:,9)+(-12).*Der(:,:,2).* ...
  Der(:,:,5).*Der(:,:,9)+2.*Der(:,:,2).^2.*Der(:,:,14))).* ...
  DiracDeltaApprox(LevelSetFct,epsilon)+kappa.*lambda.*(Der(:,:,1).^2+ ...
  Der(:,:,2).^2).^(-3).*((-2).*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).* ...
  Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5)).^2.*DiracDeltaPrimeApprox( ...
  LevelSetFct,epsilon);

% result1(abs(DiracDeltaPrimeApprox(LevelSetFct,epsilon))<1e-4)=0;
idx_flat=Der(:,:,1).^2+Der(:,:,2).^2;
result1(idx_flat==0)=0;
end

if sigma==0 || lambda==0
result2=zeros(size(LevelSetFct));
else
result2 = lambda.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*((-1).*(Der(:,:,1).^2+ ...
  Der(:,:,2).^2).^(3/2).*(Der(:,:,3)+Der(:,:,5))+dl0m.*((-2).*Der(:,:,1).* ...
  Der(:,:,4).*Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5))).* ...
  sigma.*DiracDeltaApprox(LevelSetFct,epsilon)+(-1/2).*lambda.*((-1) ...
  .*dl0m.^2+Der(:,:,1).^2+Der(:,:,2).^2).*sigma.*DiracDeltaPrimeApprox( ...
  LevelSetFct,epsilon);

% result2(abs(DiracDeltaApprox(LevelSetFct,epsilon))<1e-4)=0;
end

result = result1+result2+(-1).*BandWidth.*c3.^2.*lambdaContour.*(Der(:,:,1).^2+Der(:,:,2).^2).^( ...
  -3/2).*(LevelSetFct.^2+BandWidth.^2.*(Der(:,:,1).^2+Der(:,:,2).^2)).^( ...
  -3).*(BandWidth.^4.*(Der(:,:,1).^2+Der(:,:,2).^2).^2.*(6.*Der(:,:,1).* ...
  Der(:,:,4).*Der(:,:,2)+(-1).*Der(:,:,2).^2.*(Der(:,:,3)+(-2).*Der(:,:,5))+ ...
  Der(:,:,1).^2.*(2.*Der(:,:,3)+(-1).*Der(:,:,5)))+LevelSetFct.^4.*((-2).* ...
  Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+Der(:,:,1).^2.* ...
  Der(:,:,5))+(-2).*BandWidth.^2.*LevelSetFct.*(Der(:,:,1).^2+Der(:,:,2).^2) ...
  .*((-4).*Der(:,:,1).^4+6.*LevelSetFct.*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+( ...
  -4).*Der(:,:,2).^4+Der(:,:,1).^2.*(3.*LevelSetFct.*Der(:,:,3)+(-8).* ...
  Der(:,:,2).^2)+3.*LevelSetFct.*Der(:,:,2).^2.*Der(:,:,5))).*pi.^(-1)+(-1) ...
  .*BandWidth.*Imagee.^2.*(lambdaContour+(-1).*lambdaOutside).*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*(LevelSetFct.^2+BandWidth.^2.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2)).^(-3).*(BandWidth.^4.*(Der(:,:,1).^2+ ...
  Der(:,:,2).^2).^2.*(6.*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+(-1).*Der(:,:,2).^2.*( ...
  Der(:,:,3)+(-2).*Der(:,:,5))+Der(:,:,1).^2.*(2.*Der(:,:,3)+(-1).*Der(:,:,5))) ...
  +LevelSetFct.^4.*((-2).*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).* ...
  Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5))+(-2).*BandWidth.^2.*LevelSetFct.* ...
  (Der(:,:,1).^2+Der(:,:,2).^2).*((-4).*Der(:,:,1).^4+6.*LevelSetFct.* ...
  Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+(-4).*Der(:,:,2).^4+Der(:,:,1).^2.*(3.* ...
  LevelSetFct.*Der(:,:,3)+(-8).*Der(:,:,2).^2)+3.*LevelSetFct.* ...
  Der(:,:,2).^2.*Der(:,:,5))).*pi.^(-1)+BandWidth.*c2.*lambdaOutside.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*(LevelSetFct.^2+BandWidth.^2.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2)).^(-3).*(2.*ImageeDer(:,:,1).*Der(:,:,1).*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).*((-1).*LevelSetFct.^4+BandWidth.^4.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^2)+BandWidth.^4.*(Der(:,:,1).^2+Der(:,:,2).^2) ...
  .^2.*(2.*ImageeDer(:,:,2).*Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2)+c2.*(6.* ...
  Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+(-1).*Der(:,:,2).^2.*(Der(:,:,3)+(-2).* ...
  Der(:,:,5))+Der(:,:,1).^2.*(2.*Der(:,:,3)+(-1).*Der(:,:,5))))+(-2).* ...
  BandWidth.^2.*c2.*LevelSetFct.*(Der(:,:,1).^2+Der(:,:,2).^2).*((-4).* ...
  Der(:,:,1).^4+6.*LevelSetFct.*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+(-4).* ...
  Der(:,:,2).^4+Der(:,:,1).^2.*(3.*LevelSetFct.*Der(:,:,3)+(-8).*Der(:,:,2).^2) ...
  +3.*LevelSetFct.*Der(:,:,2).^2.*Der(:,:,5))+LevelSetFct.^4.*((-2).* ...
  ImageeDer(:,:,2).*Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2)+c2.*((-2).*Der(:,:,1).* ...
  Der(:,:,4).*Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5)))).* ...
  pi.^(-1)+(-2).*BandWidth.*Imagee.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2) ...
  .*(LevelSetFct.^2+BandWidth.^2.*(Der(:,:,1).^2+Der(:,:,2).^2)).^(-3).*(( ...
  -1).*ImageeDer(:,:,1).*(lambdaContour+(-1).*lambdaOutside).*Der(:,:,1).*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).*((-1).*LevelSetFct.^4+BandWidth.^4.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^2)+BandWidth.^4.*(Der(:,:,1).^2+Der(:,:,2).^2) ...
  .^2.*((-1).*ImageeDer(:,:,2).*(lambdaContour+(-1).*lambdaOutside).* ...
  Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2)+c2.*lambdaOutside.*(6.*Der(:,:,1).* ...
  Der(:,:,4).*Der(:,:,2)+(-1).*Der(:,:,2).^2.*(Der(:,:,3)+(-2).*Der(:,:,5))+ ...
  Der(:,:,1).^2.*(2.*Der(:,:,3)+(-1).*Der(:,:,5))))+(-2).*BandWidth.^2.* ...
  c2.*lambdaOutside.*LevelSetFct.*(Der(:,:,1).^2+Der(:,:,2).^2).*((-4).* ...
  Der(:,:,1).^4+6.*LevelSetFct.*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+(-4).* ...
  Der(:,:,2).^4+Der(:,:,1).^2.*(3.*LevelSetFct.*Der(:,:,3)+(-8).*Der(:,:,2).^2) ...
  +3.*LevelSetFct.*Der(:,:,2).^2.*Der(:,:,5))+LevelSetFct.^4.*( ...
  ImageeDer(:,:,2).*(lambdaContour+(-1).*lambdaOutside).*Der(:,:,2).*( ...
  Der(:,:,1).^2+Der(:,:,2).^2)+c2.*lambdaOutside.*((-2).*Der(:,:,1).* ...
  Der(:,:,4).*Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5)))).* ...
  pi.^(-1)+2.*BandWidth.*c3.*lambdaContour.*(Der(:,:,1).^2+Der(:,:,2).^2) ...
  .^(-3/2).*(LevelSetFct.^2+BandWidth.^2.*(Der(:,:,1).^2+Der(:,:,2).^2)) ...
  .^(-3).*((-1).*ImageeDer(:,:,1).*Der(:,:,1).*(Der(:,:,1).^2+Der(:,:,2).^2).*((-1) ...
  .*LevelSetFct.^4+BandWidth.^4.*(Der(:,:,1).^2+Der(:,:,2).^2).^2)+(-2).* ...
  BandWidth.^2.*Imagee.*LevelSetFct.*(Der(:,:,1).^2+Der(:,:,2).^2).*((-4) ...
  .*Der(:,:,1).^4+6.*LevelSetFct.*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+(-4).* ...
  Der(:,:,2).^4+Der(:,:,1).^2.*(3.*LevelSetFct.*Der(:,:,3)+(-8).*Der(:,:,2).^2) ...
  +3.*LevelSetFct.*Der(:,:,2).^2.*Der(:,:,5))+LevelSetFct.^4.*( ...
  ImageeDer(:,:,2).*Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2)+Imagee.*((-2).* ...
  Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+Der(:,:,1).^2.* ...
  Der(:,:,5)))+(-1).*BandWidth.^4.*(Der(:,:,1).^2+Der(:,:,2).^2).^2.*( ...
  ImageeDer(:,:,2).*Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2)+Imagee.*((-6).* ...
  Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,2).^2.*(Der(:,:,3)+(-2).*Der(:,:,5))+ ...
  Der(:,:,1).^2.*((-2).*Der(:,:,3)+Der(:,:,5))))).*pi.^(-1);

end