function [result]=mathematica_generated_eq2(x,dx,dxx,dxxx,dxxxx,y,dy,dyy,dyyy,dyyyy,dl0m,ddl0m,lambda,kappa,sigma,extensionmax,lambdaInside,lambdaOutside,c1,c2)
result = 10.*(dx.^2+dy.^2).^(-7/2).*dyy.*(dxx.*dy+(-1).*dx.*dyy).^2.* ...
  kappa.*lambda+4.*dxxx.*(dx.^2+dy.^2).^(-5/2).*((-1).*dxx.*dy+dx.* ...
  dyy).*kappa.*lambda+20.*dxx.*(dx.^2+dy.^2).^(-7/2).*(dxx.*dy+(-1) ...
  .*dx.*dyy).*(dx.*dxx+dy.*dyy).*kappa.*lambda+(-70).*dy.*(dx.^2+ ...
  dy.^2).^(-9/2).*(dxx.*dy+(-1).*dx.*dyy).^2.*(dx.*dxx+dy.*dyy).* ...
  kappa.*lambda+20.*dy.*(dx.^2+dy.^2).^(-7/2).*(dxx.*dy+(-1).*dx.* ...
  dyy).*(dxxx.*dy+(-1).*dx.*dyyy).*kappa.*lambda+4.*dxx.*(dx.^2+ ...
  dy.^2).^(-5/2).*((-1).*dxxx.*dy+dx.*dyyy).*kappa.*lambda+4.*( ...
  dx.^2+dy.^2).^(-9/2).*((-2).*(dx.^2+dy.^2).*(4.*dx.^2.*dxx+(-1).* ...
  dxx.*dy.^2+5.*dx.*dy.*dyy).*((-1).*dxxx.*dy+dx.*dyyy)+(-1).*((-1) ...
  .*dxx.*dy+dx.*dyy).*(4.*dx.^4.*dxxx+3.*dx.^2.*dy.*(dxxx.*dy+(-20) ...
  .*dxx.*dyy)+dy.^3.*((-1).*dxxx.*dy+10.*dxx.*dyy)+5.*dx.*dy.^2.*( ...
  3.*dxx.^2+(-6).*dyy.^2+dy.*dyyy)+5.*dx.^3.*((-4).*dxx.^2+dyy.^2+ ...
  dy.*dyyy))+dx.*(dx.^2+dy.^2).^2.*((-1).*dxxxx.*dy+(-1).*dxxx.*dyy+ ...
  dxx.*dyyy+dx.*dyyyy)).*kappa.*lambda+(-1/2).*(dx.^2+dy.^2).^(-1/2) ...
  .*((dl0m+(-1).*sqrt(dx.^2+dy.^2)).^2).^(-1/2).*((-1).*dl0m+sqrt( ...
  dx.^2+dy.^2)).*dyy.*lambda.*sigma+(1/2).*dy.*(dx.^2+dy.^2).^(-3/2) ...
  .*((dl0m+(-1).*sqrt(dx.^2+dy.^2)).^2).^(-1/2).*((-1).*dl0m+sqrt( ...
  dx.^2+dy.^2)).*(dx.*dxx+dy.*dyy).*lambda.*sigma+(-1).*dx.*( ...
  lambdaInside.*(c1+(-1).*ImageF(x,y)).^2+(-1).*lambdaOutside.*(c2+( ...
  -1).*ImageF(x,y)).^2);

end