function [result]=mathematica_generated_eq1(x,dx,dxx,dxxx,dxxxx,y,dy,dyy,dyyy,dyyyy,dl0m,ddl0m,lambda,kappa,sigma,extensionmax,lambdaInside,lambdaOutside,c1,c2)
result = 10.*dxx.*(dx.^2+dy.^2).^(-7/2).*(dxx.*dy+(-1).*dx.*dyy).^2.* ...
  kappa.*lambda+(-70).*dx.*(dx.^2+dy.^2).^(-9/2).*(dxx.*dy+(-1).* ...
  dx.*dyy).^2.*(dx.*dxx+dy.*dyy).*kappa.*lambda+20.*(dx.^2+dy.^2).^( ...
  -7/2).*dyy.*((-1).*dxx.*dy+dx.*dyy).*(dx.*dxx+dy.*dyy).*kappa.* ...
  lambda+4.*(dx.^2+dy.^2).^(-5/2).*(dxx.*dy+(-1).*dx.*dyy).*dyyy.* ...
  kappa.*lambda+4.*(dx.^2+dy.^2).^(-5/2).*dyy.*(dxxx.*dy+(-1).*dx.* ...
  dyyy).*kappa.*lambda+20.*dx.*(dx.^2+dy.^2).^(-7/2).*((-1).*dxx.* ...
  dy+dx.*dyy).*((-1).*dxxx.*dy+dx.*dyyy).*kappa.*lambda+(-4).*( ...
  dx.^2+dy.^2).^(-9/2).*(2.*(dx.^2+dy.^2).*((-5).*dx.*dxx.*dy+ ...
  dx.^2.*dyy+(-4).*dy.^2.*dyy).*((-1).*dxxx.*dy+dx.*dyyy)+(dxx.*dy+( ...
  -1).*dx.*dyy).*(5.*dx.*dy.^2.*(dxxx.*dy+(-12).*dxx.*dyy)+5.* ...
  dx.^3.*(dxxx.*dy+2.*dxx.*dyy)+(-1).*dx.^4.*dyyy+3.*dx.^2.*dy.*(( ...
  -10).*dxx.^2+5.*dyy.^2+dy.*dyyy)+dy.^3.*(5.*dxx.^2+(-20).*dyy.^2+ ...
  4.*dy.*dyyy))+dy.*(dx.^2+dy.^2).^2.*((-1).*dxxxx.*dy+(-1).*dxxx.* ...
  dyy+dxx.*dyyy+dx.*dyyyy)).*kappa.*lambda+(-1/2).*dxx.*(dx.^2+ ...
  dy.^2).^(-1/2).*((dl0m+(-1).*sqrt(dx.^2+dy.^2)).^2).^(-1/2).*((-1) ...
  .*dl0m+sqrt(dx.^2+dy.^2)).*lambda.*sigma+(1/2).*dx.*(dx.^2+dy.^2) ...
  .^(-3/2).*((dl0m+(-1).*sqrt(dx.^2+dy.^2)).^2).^(-1/2).*((-1).* ...
  dl0m+sqrt(dx.^2+dy.^2)).*(dx.*dxx+dy.*dyy).*lambda.*sigma+dy.*( ...
  lambdaInside.*(c1+(-1).*ImageF(x,y)).^2+(-1).*lambdaOutside.*(c2+( ...
  -1).*ImageF(x,y)).^2);

end