function [result]=MG_LS_Band(Der,LevelSetFct,lambda,kappa,sigma,extensionmax,lambdaInside,lambdaOutside,lambdaContour,c1,c2,c3,Imagee,ImageeDer,epsilon,BandWidth,dl0m,Der2)
idx_flat=Der(:,:,1).^2+Der(:,:,2).^2;
if kappa==0 || lambda==0
result1=zeros(size(LevelSetFct));
else
result1 = kappa.*lambda.*Der(:,:,2).^6.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-9/2).*((-7) ...
  .*Der(:,:,3).^3+2.*Der(:,:,2).*((-6).*Der(:,:,6).*Der(:,:,4)+Der(:,:,10).* ...
  Der(:,:,2))+2.*Der(:,:,3).*(20.*Der(:,:,4).^2+(-7).*Der(:,:,7).*Der(:,:,2))+ ...
  8.*Der(:,:,3).^2.*Der(:,:,5)).*DiracDeltaApprox(LevelSetFct,epsilon)+ ...
  2.*kappa.*lambda.*Der(:,:,1).*Der(:,:,2).^5.*(Der(:,:,1).^2+Der(:,:,2).^2).^( ...
  -9/2).*(69.*Der(:,:,3).^2.*Der(:,:,4)+(-40).*Der(:,:,4).^3+32.* ...
  Der(:,:,7).*Der(:,:,4).*Der(:,:,2)+(-4).*Der(:,:,11).*Der(:,:,2).^2+6.* ...
  Der(:,:,6).*Der(:,:,2).*Der(:,:,5)+Der(:,:,3).*((-13).*Der(:,:,6).*Der(:,:,2)+ ...
  14.*Der(:,:,8).*Der(:,:,2)+(-56).*Der(:,:,4).*Der(:,:,5))).* ...
  DiracDeltaApprox(LevelSetFct,epsilon)+(-2).*kappa.*lambda.* ...
  Der(:,:,1).^7.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-9/2).*(4.*Der(:,:,13).* ...
  Der(:,:,2)+7.*Der(:,:,8).*Der(:,:,5)+6.*Der(:,:,4).*Der(:,:,9)).* ...
  DiracDeltaApprox(LevelSetFct,epsilon)+(-2).*kappa.*lambda.* ...
  Der(:,:,1).^5.*Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2).^(-9/2).*(40.* ...
  Der(:,:,4).^3+Der(:,:,2).*(25.*Der(:,:,3).*Der(:,:,8)+4.*Der(:,:,11).* ...
  Der(:,:,2)+8.*Der(:,:,13).*Der(:,:,2)+7.*Der(:,:,6).*Der(:,:,5)+(-25).* ...
  Der(:,:,8).*Der(:,:,5))+Der(:,:,4).*(46.*Der(:,:,7).*Der(:,:,2)+56.* ...
  Der(:,:,3).*Der(:,:,5)+(-69).*Der(:,:,5).^2+(-14).*Der(:,:,2).*Der(:,:,9))) ...
  .*DiracDeltaApprox(LevelSetFct,epsilon)+kappa.*lambda.* ...
  Der(:,:,1).^2.*Der(:,:,2).^4.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-9/2).*(48.* ...
  Der(:,:,3).^3+28.*Der(:,:,6).*Der(:,:,4).*Der(:,:,2)+(-92).*Der(:,:,4).* ...
  Der(:,:,8).*Der(:,:,2)+4.*Der(:,:,10).*Der(:,:,2).^2+12.*Der(:,:,12).* ...
  Der(:,:,2).^2+(-101).*Der(:,:,3).^2.*Der(:,:,5)+232.*Der(:,:,4).^2.* ...
  Der(:,:,5)+(-50).*Der(:,:,7).*Der(:,:,2).*Der(:,:,5)+Der(:,:,3).*((-388).* ...
  Der(:,:,4).^2+50.*Der(:,:,7).*Der(:,:,2)+56.*Der(:,:,5).^2+(-14).* ...
  Der(:,:,2).*Der(:,:,9))).*DiracDeltaApprox(LevelSetFct,epsilon)+(-2).* ...
  kappa.*lambda.*Der(:,:,1).^3.*Der(:,:,2).^3.*(Der(:,:,1).^2+Der(:,:,2).^2).^( ...
  -9/2).*(96.*Der(:,:,3).^2.*Der(:,:,4)+(-140).*Der(:,:,4).^3+Der(:,:,3).*( ...
  13.*Der(:,:,6).*Der(:,:,2)+11.*Der(:,:,8).*Der(:,:,2)+(-218).*Der(:,:,4).* ...
  Der(:,:,5))+Der(:,:,2).*(8.*Der(:,:,11).*Der(:,:,2)+4.*Der(:,:,13).* ...
  Der(:,:,2)+Der(:,:,6).*Der(:,:,5)+(-32).*Der(:,:,8).*Der(:,:,5))+2.* ...
  Der(:,:,4).*(7.*Der(:,:,7).*Der(:,:,2)+48.*Der(:,:,5).^2+(-10).*Der(:,:,2).* ...
  Der(:,:,9))).*DiracDeltaApprox(LevelSetFct,epsilon)+2.*kappa.* ...
  lambda.*Der(:,:,1).^8.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-9/2).*Der(:,:,14).* ...
  DiracDeltaApprox(LevelSetFct,epsilon)+kappa.*lambda.*Der(:,:,1).^6.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^(-9/2).*(64.*Der(:,:,4).*Der(:,:,8).*Der(:,:,2)+ ...
  12.*Der(:,:,12).*Der(:,:,2).^2+40.*Der(:,:,4).^2.*Der(:,:,5)+28.* ...
  Der(:,:,7).*Der(:,:,2).*Der(:,:,5)+8.*Der(:,:,3).*Der(:,:,5).^2+(-7).* ...
  Der(:,:,5).^3+12.*Der(:,:,3).*Der(:,:,2).*Der(:,:,9)+(-26).*Der(:,:,2).* ...
  Der(:,:,5).*Der(:,:,9)+4.*Der(:,:,2).^2.*Der(:,:,14)).*DiracDeltaApprox( ...
  LevelSetFct,epsilon)+kappa.*lambda.*Der(:,:,1).^4.*Der(:,:,2).^2.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^(-9/2).*(56.*Der(:,:,3).^2.*Der(:,:,5)+ ...
  Der(:,:,3).*(232.*Der(:,:,4).^2+64.*Der(:,:,7).*Der(:,:,2)+(-101).* ...
  Der(:,:,5).^2+(-2).*Der(:,:,2).*Der(:,:,9))+2.*(20.*Der(:,:,6).* ...
  Der(:,:,4).*Der(:,:,2)+(-14).*Der(:,:,4).*Der(:,:,8).*Der(:,:,2)+ ...
  Der(:,:,10).*Der(:,:,2).^2+12.*Der(:,:,12).*Der(:,:,2).^2+(-194).* ...
  Der(:,:,4).^2.*Der(:,:,5)+(-11).*Der(:,:,7).*Der(:,:,2).*Der(:,:,5)+24.* ...
  Der(:,:,5).^3+(-13).*Der(:,:,2).*Der(:,:,5).*Der(:,:,9)+Der(:,:,2).^2.* ...
  Der(:,:,14))).*DiracDeltaApprox(LevelSetFct,epsilon);

% result1(abs(DiracDeltaPrimeApprox(LevelSetFct,epsilon))<1e-4)=0;
result1(idx_flat==0)=0;

end

if sigma==0 || lambda==0
result2=zeros(size(LevelSetFct));
else
result2 = (-1).*lambda.*Der(:,:,1).^3.*Der(:,:,4).*Der(:,:,2).*(Der(:,:,1).^2+ ...
  Der(:,:,2).^2).^(-3/2).*sigma.*DiracDeltaApprox(LevelSetFct,epsilon)+ ...
  (-1).*lambda.*Der(:,:,1).*Der(:,:,4).*Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2) ...
  .^(-3/2).*((-1).*dl0m.^2+Der(:,:,2).^2+2.*dl0m.*(Der(:,:,1).^2+ ...
  Der(:,:,2).^2).^(1/2)).*sigma.*DiracDeltaApprox(LevelSetFct,epsilon)+ ...
  (-1/2).*lambda.*Der(:,:,1).^4.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*(4.* ...
  Der(:,:,3)+3.*Der(:,:,5)).*sigma.*DiracDeltaApprox(LevelSetFct, ...
  epsilon)+(-1/2).*lambda.*Der(:,:,1).^2.*(Der(:,:,1).^2+Der(:,:,2).^2).^( ...
  -3/2).*(Der(:,:,3).*(7.*Der(:,:,2).^2+(-2).*dl0m.*(Der(:,:,1).^2+ ...
  Der(:,:,2).^2).^(1/2))+(dl0m.^2+7.*Der(:,:,2).^2+(-4).*dl0m.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^(1/2)).*Der(:,:,5)).*sigma.* ...
  DiracDeltaApprox(LevelSetFct,epsilon)+(-1/2).*lambda.*Der(:,:,2).^2.* ...
  (Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*(dl0m.^2.*Der(:,:,3)+(-2).*dl0m.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^(1/2).*(2.*Der(:,:,3)+Der(:,:,5))+Der(:,:,2).^2.* ...
  (3.*Der(:,:,3)+4.*Der(:,:,5))).*sigma.*DiracDeltaApprox(LevelSetFct, ...
  epsilon);

% result2(abs(DiracDeltaApprox(LevelSetFct,epsilon))<1e-4)=0;
end

result3 = result1+result2+(-1).*c3.^2.*lambdaContour.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*((-2) ...
  .*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+Der(:,:,1).^2.* ...
  Der(:,:,5)).*DiracDeltaApprox(LevelSetFct,epsilon)+(-1).*Imagee.^2.* ...
  (lambdaContour+(-1).*lambdaOutside).*(Der(:,:,1).^2+Der(:,:,2).^2).^( ...
  -3/2).*((-2).*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+ ...
  Der(:,:,1).^2.*Der(:,:,5)).*DiracDeltaApprox(LevelSetFct,epsilon)+c2.* ...
  lambdaOutside.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*((-2).* ...
  ImageeDer(:,:,1).*Der(:,:,1).*(Der(:,:,1).^2+Der(:,:,2).^2)+(-2).*ImageeDer(:,:,2).* ...
  Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2)+c2.*((-2).*Der(:,:,1).*Der(:,:,4).* ...
  Der(:,:,2)+Der(:,:,3).*Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5))).* ...
  DiracDeltaApprox(LevelSetFct,epsilon)+2.*c3.*lambdaContour.*( ...
  Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*(ImageeDer(:,:,1).*Der(:,:,1).*( ...
  Der(:,:,1).^2+Der(:,:,2).^2)+ImageeDer(:,:,2).*Der(:,:,2).*(Der(:,:,1).^2+ ...
  Der(:,:,2).^2)+Imagee.*((-2).*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).* ...
  Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5))).*DiracDeltaApprox(LevelSetFct, ...
  epsilon)+(-2).*Imagee.*(Der(:,:,1).^2+Der(:,:,2).^2).^(-3/2).*( ...
  ImageeDer(:,:,1).*(lambdaContour+(-1).*lambdaOutside).*Der(:,:,1).*( ...
  Der(:,:,1).^2+Der(:,:,2).^2)+ImageeDer(:,:,2).*(lambdaContour+(-1).* ...
  lambdaOutside).*Der(:,:,2).*(Der(:,:,1).^2+Der(:,:,2).^2)+c2.* ...
  lambdaOutside.*((-2).*Der(:,:,1).*Der(:,:,4).*Der(:,:,2)+Der(:,:,3).* ...
  Der(:,:,2).^2+Der(:,:,1).^2.*Der(:,:,5))).*DiracDeltaApprox(LevelSetFct, ...
  epsilon);

result3(idx_flat==0)=0;
result = result1+result2+result3;
end