function [result]=MG_LS_Band(Der,LevelSetFct,lambda,kappa,sigma,extensionmax,lambdaInside,lambdaOutside,lambdaContour,c1,c2,c3,Imagee,ImageeDer,epsilon,BandWidth,dl0m,Der2)
idx_flat=Der(:,:,1).^2+Der(:,:,2).^2;
if kappa==0 || lambda==0
result1=zeros(size(LevelSetFct));
else
result1 = (-2).*BandWidth.^(-1).*kappa.*lambda.*Der(:,:,3).^2.*DiracDelta( ...
  BandWidth+(-2).*LevelSetFct)+6.*BandWidth.^(-1).*kappa.*lambda.* ...
  Der(:,:,1).*Der(:,:,6).*DiracDelta(BandWidth+(-2).*LevelSetFct)+6.* ...
  BandWidth.^(-1).*kappa.*lambda.*Der(:,:,1).*Der(:,:,8).*DiracDelta( ...
  BandWidth+(-2).*LevelSetFct)+6.*BandWidth.^(-1).*kappa.*lambda.* ...
  Der(:,:,7).*Der(:,:,2).*DiracDelta(BandWidth+(-2).*LevelSetFct)+(-4).* ...
  BandWidth.^(-1).*kappa.*lambda.*Der(:,:,3).*Der(:,:,5).*DiracDelta( ...
  BandWidth+(-2).*LevelSetFct)+(-2).*BandWidth.^(-1).*kappa.* ...
  lambda.*Der(:,:,5).^2.*DiracDelta(BandWidth+(-2).*LevelSetFct)+6.* ...
  BandWidth.^(-1).*kappa.*lambda.*Der(:,:,2).*Der(:,:,9).*DiracDelta( ...
  BandWidth+(-2).*LevelSetFct)+2.*BandWidth.^(-1).*kappa.*lambda.* ...
  Der(:,:,3).^2.*DiracDelta(BandWidth+2.*LevelSetFct)+(-6).* ...
  BandWidth.^(-1).*kappa.*lambda.*Der(:,:,1).*Der(:,:,6).*DiracDelta( ...
  BandWidth+2.*LevelSetFct)+(-6).*BandWidth.^(-1).*kappa.*lambda.* ...
  Der(:,:,1).*Der(:,:,8).*DiracDelta(BandWidth+2.*LevelSetFct)+(-6).* ...
  BandWidth.^(-1).*kappa.*lambda.*Der(:,:,7).*Der(:,:,2).*DiracDelta( ...
  BandWidth+2.*LevelSetFct)+4.*BandWidth.^(-1).*kappa.*lambda.* ...
  Der(:,:,3).*Der(:,:,5).*DiracDelta(BandWidth+2.*LevelSetFct)+2.* ...
  BandWidth.^(-1).*kappa.*lambda.*Der(:,:,5).^2.*DiracDelta(BandWidth+ ...
  2.*LevelSetFct)+(-6).*BandWidth.^(-1).*kappa.*lambda.*Der(:,:,2).* ...
  Der(:,:,9).*DiracDelta(BandWidth+2.*LevelSetFct)+(-1).*BandWidth.^( ...
  -1).*kappa.*lambda.*(BandWidth.*(Der(:,:,3)+Der(:,:,5)).* ...
  DiracDeltaApprox(LevelSetFct,epsilon)+(-1).*(Der(:,:,10)+2.* ...
  Der(:,:,12)+Der(:,:,14)).*(HeavisideTheta((-1/2).*BandWidth+ ...
  LevelSetFct)+(-1).*HeavisideTheta((1/2).*BandWidth+LevelSetFct))); ...
  

% result1(abs(DiracDeltaPrimeApprox(LevelSetFct,epsilon))<1e-4)=0;
result1(idx_flat==0)=0;

end

if sigma==0 || lambda==0
result2=zeros(size(LevelSetFct));
else
result2 = 0;

% result2(abs(DiracDeltaApprox(LevelSetFct,epsilon))<1e-4)=0;
end

result3 = result1+result2+c3.^2.*lambdaContour.*DiracDeltaApprox(LevelSetFct,epsilon)+(-2).* ...
  c3.*Imagee.*lambdaContour.*DiracDeltaApprox(LevelSetFct,epsilon)+ ...
  Imagee.^2.*(lambdaContour+(-1).*lambdaOutside).*DiracDeltaApprox( ...
  LevelSetFct,epsilon)+(-1).*c2.^2.*lambdaOutside.*DiracDeltaApprox( ...
  LevelSetFct,epsilon)+2.*c2.*Imagee.*lambdaOutside.* ...
  DiracDeltaApprox(LevelSetFct,epsilon);

result3(idx_flat==0)=0;
result = result1+result2+result3;
end