function TVD_RK3_scheme(lambdaInside,area_diff_stop,max_iter,small_step_limit,display_every_n,energy_every_n,...
            text_each_ite,check_area_every,Psize,extensionmax,resample_each,Cxm,Cym,dl0m,no_final_energy,no_final_energy2,...
            antidivergence,evol_eq_sign,last_disp_Cxm,last_disp_Cym,adaptative_new_step,...
            shift,lambda,kappa,sigma_used,lambdaOutside,c1,c2,timestep,Imagee,real_t,su,old_su,...
            dxa,dx,dxxs,dxx,dxxxa,dxxx,dxxxxs,dxxxx,...
            dya,dy,dyys,dyy,dyyya,dyyy,dyyyys,dyyyy,...
            ddl0ma,ddl0m,t,tt,...
            new_step_,time_step)
% this is the simplest scheme, just Euler step with an home made way of determining step size in time.
% see osher et Fedkiw p 38
% assumed that all is time independent but the level set function

   global Level_set_fct
   LS0=Level_set_fct;
%% implementation
    % first Euler step
    LS1=Level_set_fct-time_step*evol_eq_sign*new_step_;
    
    % second Euler step
    Level_set_fct=LS1;
     new_step_=virtual_time_loop_LS_Chan_Vese_ZBand_curv_flat_nio_cont_1_step(lambdaInside,area_diff_stop,max_iter,small_step_limit,display_every_n,energy_every_n,...
            text_each_ite,check_area_every,Psize,extensionmax,resample_each,Cxm,Cym,dl0m,no_final_energy,no_final_energy2,...
            antidivergence,evol_eq_sign,last_disp_Cxm,last_disp_Cym,adaptative_new_step,...
            shift,lambda,kappa,sigma_used,lambdaOutside,c1,c2,timestep,Imagee,real_t,su,old_su,...
            dxa,dx,dxxs,dxx,dxxxa,dxxx,dxxxxs,dxxxx,...
            dya,dy,dyys,dyy,dyyya,dyyy,dyyyys,dyyyy,...
            ddl0ma,ddl0m,t,tt,param_set);       
     LS2=Level_set_fct-time_step*evol_eq_sign*new_step_;
     
     % averaging
     LS0p5=3/4*LS0+1/4*LS2;

     % third Euler step
     Level_set_fct=LS0p5;
     new_step_=virtual_time_loop_LS_Chan_Vese_ZBand_curv_flat_nio_cont_1_step(lambdaInside,area_diff_stop,max_iter,small_step_limit,display_every_n,energy_every_n,...
            text_each_ite,check_area_every,Psize,extensionmax,resample_each,Cxm,Cym,dl0m,no_final_energy,no_final_energy2,...
            antidivergence,evol_eq_sign,last_disp_Cxm,last_disp_Cym,adaptative_new_step,...
            shift,lambda,kappa,sigma_used,lambdaOutside,c1,c2,timestep,Imagee,real_t,su,old_su,...
            dxa,dx,dxxs,dxx,dxxxa,dxxx,dxxxxs,dxxxx,...
            dya,dy,dyys,dyy,dyyya,dyyy,dyyyys,dyyyy,...
            ddl0ma,ddl0m,t,tt,param_set);       
    LS1p5=Level_set_fct-time_step*evol_eq_sign*new_step_;

     % averaging
    Level_set_fct=1/3*LS0+2/3*LS1p5;

end
