function [Cxm,Cym,su,old_su]=...
            virtual_time_loop_LS_Chan_Vese_ZBand_curvature_flat_nio_cont(lambdaInside,area_diff_stop,max_iter,small_step_limit,display_every_n,energy_every_n,...
            text_each_ite,check_area_every,Psize,extensionmax,resample_each,Cxm,Cym,dl0m,no_final_energy,no_final_energy2,...
            antidivergence,evol_eq_sign,last_disp_Cxm,last_disp_Cym,adaptative_new_step,...
            shift,lambda,kappa,sigma_used,lambdaOutside,c1,c2,timestep,Imagee,real_t,su,old_su,...
            dxa,dx,dxxs,dxx,dxxxa,dxxx,dxxxxs,dxxxx,...
            dya,dy,dyys,dyy,dyyya,dyyy,dyyyys,dyyyy,...
            ddl0ma,ddl0m,t,tt,param_set)

% this is the scheme framework

%% initialization
global rns;
global Image_param;
global Level_set_fct
global maxLS

rns=1; % needed for calling procedure to report the size of the step correctly

%% make one step in space (always needed, in the Euler way)
 new_step_=virtual_time_loop_LS_Chan_Vese_ZBand_curv_flat_nio_cont_1_step(lambdaInside,area_diff_stop,max_iter,small_step_limit,display_every_n,energy_every_n,...
            text_each_ite,check_area_every,Psize,extensionmax,resample_each,Cxm,Cym,dl0m,no_final_energy,no_final_energy2,...
            antidivergence,evol_eq_sign,last_disp_Cxm,last_disp_Cym,adaptative_new_step,...
            shift,lambda,kappa,sigma_used,lambdaOutside,c1,c2,timestep,Imagee,real_t,su,old_su,...
            dxa,dx,dxxs,dxx,dxxxa,dxxx,dxxxxs,dxxxx,...
            dya,dy,dyys,dyy,dyyya,dyyy,dyyyys,dyyyy,...
            ddl0ma,ddl0m,t,tt,param_set);       
global heuristic_params;
if length(heuristic_params)>1 % we run preliminary params tuning
    return;
end

%% determine step size in time        
       
new_step=Image_param.get_time_step_size(new_step_,param_set);

%% numerical scheme call
Image_param.numerical_scheme(lambdaInside,area_diff_stop,max_iter,small_step_limit,display_every_n,energy_every_n,...
            text_each_ite,check_area_every,Psize,extensionmax,resample_each,Cxm,Cym,dl0m,no_final_energy,no_final_energy2,...
            antidivergence,evol_eq_sign,last_disp_Cxm,last_disp_Cym,adaptative_new_step,...
            shift,lambda,kappa,sigma_used,lambdaOutside,c1,c2,timestep,Imagee,real_t,su,old_su,...
            dxa,dx,dxxs,dxx,dxxxa,dxxx,dxxxxs,dxxxx,...
            dya,dy,dyys,dyy,dyyya,dyyy,dyyyys,dyyyy,...
            ddl0ma,ddl0m,t,tt,...
            new_step_,new_step,param_set);
        
    %% level set is a  signed distance, so there should not be crazy values
    % Level_set_fct(Level_set_fct(:,:)>maxLS)=maxLS;
    % Level_set_fct(Level_set_fct(:,:)<maxLS)=-maxLS;
    
%% secure evolution     
    if  abs(Level_set_fct(:,:))>10*maxLS  
        warning_perso('divergence detected in Level set, resampling to signed distance');
        resample_AC;
    end
end